const shortAbbrevations = {
  userAgent: 'ua',
  appVersion: 'av',
  rtt: 'gr',
  windowSize: 'ws',
  pluginsLength: 'pl',
  pluginsArray: 'pa',
  errorTrace: 'et',
  productSub: 'ps',
  windowExternal: 'we',
  mimeTypesConsistent: 'mm',
  evalLength: 'ev',
  webGL: 'wg',
  webDriver: 'wd',
  languages: 'lg',
  notificationPermissions: 'np',
  documentElementKeys: 'ek',
  functionBind: 'fb',
  process: 'gp',
  distinctiveProps: 'dp',
  batteryInstance: 'bi',
  isLocalStorage: 'ls',
  isSessionStorage: 'is',
  timezone: 'tz',
  touchEventFp: 'te',
}

export default shortAbbrevations
